### ISSUE TITLE
CaseClauseError with return type of Ecto.Changeset.t()

### ISSUE THREAD

**Issue by randycoulman** [msz/hammox#57]
I'm using the latest commit on the `master` branch.

I have a function in a behaviour that returns an Ecto Changeset.  If I attempt to wrap this function with `Hammox.protect` while testing it, I get the following error message and stack trace. I've reproduced this error in a separate repo that I can publish somewhere if it would be helpful; important extracts are below.

I'm happy to try to help track this down, but I'm not sure of the best way to do that. Tips welcome!

```
     ** (CaseClauseError) no case clause matching: [{:type, 441, :map_field_exact, [{:atom, 0, :__struct__}, {:type, 441, :atom, []}]}]
     stacktrace:
       (hammox 0.2.5) lib/hammox/type_engine.ex:346: Hammox.TypeEngine.match_type/2
       (hammox 0.2.5) lib/hammox/type_engine.ex:12: anonymous fn/3 in Hammox.TypeEngine.match_type/2
       (elixir 1.10.0) lib/enum.ex:3686: Enumerable.List.reduce/3
       (elixir 1.10.0) lib/enum.ex:2161: Enum.reduce_while/3
       (hammox 0.2.5) lib/hammox/type_engine.ex:11: Hammox.TypeEngine.match_type/2
       (hammox 0.2.5) lib/hammox/type_engine.ex:12: anonymous fn/3 in Hammox.TypeEngine.match_type/2
       (elixir 1.10.0) lib/enum.ex:3686: Enumerable.List.reduce/3
       (elixir 1.10.0) lib/enum.ex:2161: Enum.reduce_while/3
       (hammox 0.2.5) lib/hammox/type_engine.ex:11: Hammox.TypeEngine.match_type/2
       (hammox 0.2.5) lib/hammox/type_engine.ex:375: anonymous fn/3 in Hammox.TypeEngine.match_type/2
       (elixir 1.10.0) lib/enum.ex:1400: anonymous fn/3 in Enum.map/2
       (stdlib 3.11.1) maps.erl:232: :maps.fold_1/3
       (elixir 1.10.0) lib/enum.ex:2127: Enum.map/2
       (hammox 0.2.5) lib/hammox/type_engine.ex:374: anonymous fn/2 in Hammox.TypeEngine.match_type/2
       (elixir 1.10.0) lib/enum.ex:3686: Enumerable.List.reduce/3
       (elixir 1.10.0) lib/enum.ex:2161: Enum.reduce_while/3
       (hammox 0.2.5) lib/hammox/type_engine.ex:372: Hammox.TypeEngine.match_type/2
       (hammox 0.2.5) lib/hammox.ex:359: Hammox.match_return_value/2
       (hammox 0.2.5) lib/hammox.ex:327: Hammox.match_call/3
       (hammox 0.2.5) lib/hammox.ex:311: anonymous fn/4 in Hammox.check_call/3
```

Here are the behavior and implementation:

```elixir
defmodule HammoxTest.Friends.Impl do
  alias HammoxTest.Friends.Person

  @callback change_person(Person.t(), map()) :: Ecto.Changeset.t()
end

defmodule HammoxTest.Friends do
  alias HammoxTest.Friends.{Impl, Person}

  @behaviour Impl

  @impl Impl
  def change_person(%Person{} = person, attrs \\ %{}) do
    person
    |> Person.changeset(attrs)
  end
end

defmodule HammoxTest.Friends.Person do
  use Ecto.Schema

  @type t :: %__MODULE__{
          first_name: String.t() | nil,
          last_name: String.t() | nil,
          age: integer() | nil
        }

  schema "people" do
    field(:first_name, :string)
    field(:last_name, :string)
    field(:age, :integer)
  end

  def changeset(person, attrs \\ %{}) do
    person
    |> Ecto.Changeset.cast(attrs, [:first_name, :last_name, :age])
    |> Ecto.Changeset.validate_required([:first_name, :last_name])
  end
end
```

And here is the test:
```elixir
defmodule HammoxTest.FriendsTest do
  use ExUnit.Case

  import Hammox

  alias HammoxTest.Friends
  alias HammoxTest.Friends.{Impl, Person}

  test "can I type-check a changeset?" do
    change_person_2 = protect({Friends, :change_person, 2}, Impl)

    changeset = change_person_2.(%Person{}, %{age: 42})

    assert changeset.valid?
  end
end
```

**Comment by msz** [comment]
Thank you for the report and the detailed reproduction case! I haven't tried it yet but you should never get this kind of exception so it's definitely a bug.

**Comment by randycoulman** [comment]
After reading the discussion on #63, I retested my sample application with ecto 3.5.4 and hammox 0.3, but I still see the same error.

What's the best way for me to dig in and try to resolve this issue myself? Is there any documentation about the structure of the type information that you find particularly useful here?

**Comment by msz** [comment]
Sorry, didn't have the time to get to fixing this yet. You're welcome to take a stab at it if you want!

Personally the way I developed the whole thing is:
- Read some references on the Elixir AST in general
- Set up the type reading mechanism
- Wrote minimal test cases and inspected the resulting typespec AST structures in them
- Wrote match cases for those typespec AST structures

Should work to fix this case too!

**Comment by randycoulman** [comment]
I spent a little bit of time on this. I still don't fully understand what all of the code is doing, but I have a few clues.

The error is coming from the `match_type` function head at https://github.com/msz/hammox/blob/master/lib/hammox/type_engine.ex#L340-L356.

It looks like it's trying to match the following typespec from `Ecto.Schema`:

```elixir
 schema() :: %{
  optional(atom()) => any(),
  :__struct__ => atom(),
  :__meta__ => Ecto.Schema.Metadata.t()
}
```

The AST fragment for that typespec looks like this:

```elixir
   type: {:schema,
    {:type, 441, :map,
     [
       {:type, 441, :map_field_assoc,
        [{:type, 441, :atom, []}, {:type, 441, :any, []}]},
       {:type, 441, :map_field_exact,
        [{:atom, 0, :__struct__}, {:type, 441, :atom, []}]},
       {:type, 441, :map_field_exact,
        [
          {:atom, 0, :__meta__},
          {:remote_type, 441,
           [{:atom, 0, Ecto.Schema.Metadata}, {:atom, 0, :t}, []]}
        ]}
     ]}, []},
```

If I'm understanding this properly, I think that the code in `match_type` is assuming that it's looking at an actual struct, where the `__struct__` key is an atom and it gets confused by a typedef that specifies a `__struct__` property instead.

I don't understand enough of the type engine to know how to fix this.

We could add another clause to the `case` statement to match this case, but I'm not sure what the right action would be.

We could modify the `split_with` clause above the `case` statement to not treat this case as a `struct_field_type`, but I'm not sure that's right either.

I'm willing to try to fix this, but could use some guidance on the best direction to go.

**Comment by randycoulman** [comment]
@msz Sorry to nag about this, but I'd really like to get this fixed so we can take advantage of the new protection on `stub`. Do you have any guidance on the right way to fix this issue given what I found above?  I'm happy to do the necessary work to get a PR up, but not sure what direction to go.

I think that we probably need one or two recursive calls to `match_type` for this new case, but not positive about that.

**Comment by randycoulman** [comment]
@msz I had an idea and it looks like it works OK.  See #64.
